config/routes.rb
Rails.application.routes.draw do
  resources :play_lists
  resources :videos
  resources :payusers
  resources :commends
  devise_for :users ,:controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  
  get 'home/index', to: 'home#index', as: :home
  resources :tracks
  resources :albums
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get 'albums/:album_id/show_albums', to: 'albums#show', as: :album_show
	get 'artists/:id/show_album', to: 'artists#show_album', as: :artists_show_album
	get 'artists/:id/show_track', to: 'artists#show_track', as: :artists_show_track
	get 'artists/:id/show_video', to: 'artists#show_video', as: :artists_show_video
	match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
	root 'home#index'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :tracks ,dependent: :destroy
  has_many :commends ,dependent: :destroy
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :albums ,dependent: :destroy
end

app/models/commend.rb
class Commend < ApplicationRecord
  # resourcify
  # include Authority::Abilities
  belongs_to :user
  belongs_to :album
	

end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/payuser.rb
class Payuser < ApplicationRecord
end

app/models/play_list.rb
class PlayList < ApplicationRecord
  belongs_to :user
  belongs_to :track
	
	def overlap?
	PlayList.where(user_id: self.user_id, track_id: self.track_id).size >0
	end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/social_auth.rb
class SocialAuth < ApplicationRecord
	belongs_to :user
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
  has_one :video
  has_many :users, :through => :play_lists
end

app/models/user.rb
class User < ApplicationRecord
  # rolify
  # include Authority::UserAbilities	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable,:omniauthable
  has_many :identities, dependent: :destroy
  has_many :commends, dependent: :destroy
  has_many :tracks, :through => :play_lists
 # after_create :set_default_role, if: Proc.new { User.count > 1 }

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  validates_presence_of :name
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.info.name || auth.extra.nickname ||  auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end

    user

  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

 #  private
 #  def set_default_role
 #    add_role :user
 #  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :track
end

app/controllers/play_lists_controller.rb
class PlayListsController < ApplicationController
  before_action :set_play_list, only: %i[ show edit update destroy ]

  # GET /play_lists or /play_lists.json
  def index
    @play_lists = PlayList.all
	@my_play_lists = PlayList.where(user_id: current_user.id)
	  if user_signed_in? 
		@pay_t = Payuser.where(user_id: current_user.id).size > 0
		end
	
  end

  # GET /play_lists/1 or /play_lists/1.json
  def show
  end

  # GET /play_lists/new
  def new
    @play_list = PlayList.new
  end

  # GET /play_lists/1/edit
  def edit
  end

  # POST /play_lists or /play_lists.json
  def create
    @play_list = PlayList.new(play_list_params)
	

    respond_to do |format|
      if @play_list.overlap?
        format.html { redirect_to tracks_path, notice: "이미 마이 뮤직에 들어가있는 음악입니다." }
      else
		  @play_list.save
     	  format.html { redirect_to tracks_path, notice: "마이 뮤직에 포함 완료" }
      
        end
    end
  end

  # PATCH/PUT /play_lists/1 or /play_lists/1.json
  def update
    respond_to do |format|
      if @play_list.update(play_list_params)
        format.html { redirect_to play_list_url(@play_list), notice: "Play list was successfully updated." }
        format.json { render :show, status: :ok, location: @play_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @play_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /play_lists/1 or /play_lists/1.json
  def destroy
    @play_list.destroy

    respond_to do |format|
      format.html { redirect_to play_lists_url, notice: "Play list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play_list
      @play_list = PlayList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def play_list_params
      params.require(:play_list).permit(:user_id, :track_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/commends_helper.rb
module CommendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payusers_helper.rb
module PayusersHelper
end

app/helpers/play_lists_helper.rb
module PlayListsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/play_lists/_form.html.erb
<%= form_with(model: play_list, local: true) do |form| %>
  <% if play_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(play_list.errors.count, "error") %> prohibited this play_list from being saved:</h2>

      <ul>
      <% play_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :track_id %>
    <%= form.text_field :track_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/play_lists/edit.html.erb
<h1>Editing Play List</h1>

<%= render 'form', play_list: @play_list %>

<%= link_to 'Show', @play_list %> |
<%= link_to 'Back', play_lists_path %>

app/views/play_lists/index.html.erb
<p id="notice"><%= notice %></p>
<div class = "cont_wrap" style="margin:0 auto; background:0; zoom:1;">
	<div class = "fold" style = "padding: 0 20px; position:relative; width:1008px; margin:0 auto;">
		<div class = "cont" style = "position; relative; z-index:10; display:block; width:1008px; min-height:800px; padding:29px 0 88px; zoom:1;">
<h2 style="color: #1a1a1a; font-weight: bold;font-size: 24px;line-height: 30px; font-family:'Malgun Gothic'; padding-bottom:25px;">
	마이뮤직
			</h2>
			  <div class="field" style="width:612px; height:130px;">
				  <div style="float:left; width:250px;">
			<img style="position: relative;display: block;width: 98px;height: 98px; float:left;" src="<%= current_user.profile_img%>">
	  <span style="font-size: 23px;color:#1a1a1a;font-weight: 500;line-height: 30px; margin-left:15px;"><%= current_user.name %>님</span>
			<% if @pay_t%>
				<p style="float:left;display: inline-block;width: auto;max-width: 190px;white-space: nowrap;">스트리밍클럽 사용중</p>
				<% else%>
				<p style="width: auto; max-width:183px; padding-left:115px;">결제 후 이용 가능</p>
				<%end%>
				</div>
			</div>
			<div class="user_info">
				<h2 style="color: #1a1a1a; font-weight: bold;font-size: 24px;line-height: 30px; font-family:'Malgun Gothic'; padding-bottom:25px; border-bottom:1px solid;">
	나의 플레이 리스트
			</h2>
			</div>
			<table style =" width:100%; border-collapse: collapse; border-spacing:0;" border="1">
				<thead>
					<tr>
						<th style="width:15px;height: 48px; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; color: #606060; font-size: 13px; text-align:left; vertical-align:middle; ">
							<div class="wrap t_right" style = "padding-top:2px; text-align:right;">
								<input type="checkbox" style= "margin:0;">
							</div>
						</th>
						<th style = "width:62px;  height: 48px; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; color: #606060; font-size: 13px; text-align: left; vertical-align: middle;">
							<div style="padding-top: 2px;">
								<span style="display: inline-block; width:32px; padding: 0 18px 0 12px;">번호</span>
							</div>
						</th>
					
						<th style = "width:24px; height: 48px; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; color: #606060; font-size: 13px; text-align: left; vertical-align: middle;">
							<div class ="none"style="padding-top: 2px;position: absolute;top: -5000em;left: 0;width: 0;height: 0;font-size: 0;line-height: 0;overflow: hidden;">
								곡상세가기
							</div>
						</th>
						<th style = "width:558px;height: 48px; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; color: #606060; font-size: 13px; text-align: left; vertical-align: middle;">
							<div style="padding-top: 2px; padding-left: 12px;">
								곡정보
							</div>
						</th>
						
						<th style = "width:111px; height: 48px; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; color: #606060; font-size: 13px; text-align: left; vertical-align: middle;">
							<div style="padding-top: 2px; padding-left: 30px;">
								좋아요
							</div>
						</th>
						<th style = "width:58px; height: 48px; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; color: #606060; font-size: 13px; text-align: left; vertical-align: middle;">
							<div style="padding-top: 2px; text-align:center;">
								듣기
							</div>
						</th>
						<th style = "width:52px; height: 48px; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; color: #606060; font-size: 13px; text-align: left; vertical-align: middle;">
							<div style="padding-top: 2px; text-align:center;">
								담기
							</div>
						</th>
						<th style = "width:52px; height: 48px; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; color: #606060; font-size: 13px; text-align: left; vertical-align: middle;">
							<div style="padding-top: 2px; text-align:center;">
								다운
							</div>
						</th>
						<th style = "width:52px; height: 48px; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; color: #606060; font-size: 13px; text-align: left; vertical-align: middle;">
							<div style="padding-top: 2px; text-align:center;">
								뮤비
							</div>
						</th>
					</tr>
				</thead>
			
			<% a = 1 %>
			<% @my_play_lists.each do |play_list| %>
			<tbody>
				<tr style="display: table-row;">
					<td style="height:84px; border-bottom:1px solid #f2f2f2; text-algin:left; vertical-algin:middle;">
							<div style = "text-algin: right; margin-top:31px;">
								<input type="checkbox" style="border: initial;background-color: initial;cursor: default;appearance: auto;box-sizing: border-box; vertical-algin:middle;" >
							</div>
						</td>
					<td style="text-align: left; vertical-align: middle; height:84px; border-bottom:1px solid #f2f2f2;">
							<div class="atist_id" style="text-align:center;">
								<span style="display: inline-block;padding-top: 5px;color: #333;font-size: 18px;width: 32px;padding: 0 18px 0 12px;" ><%= a %></span>
								<% a = a + 1 %>
							</div>
					</td>
					<td style="border-bottom:1px solid #f2f2f2; text-algin:left; vertical-algin:middle;">
							<div class="wrap" style="width:50px;">
							</div>
						</td>
					<td style="border-bottom:1px solid #f2f2f2;vertical-align: middle;">
							<div class="wrap" style="text-algin:left;">
								<div class="wrap_song_info" style="display: inline-block;width: 100%;margin-left: 12px;vertical-align: middle;">
									<div class="ellipsis" style="display: inline-block;padding-right: 1px;vertical-align: middle;white-space: nowrap;text-overflow: ellipsis;word-wrap: normal;overflow: hidden;">
										<span><%= link_to play_list.track.title ,track_path(play_list.track.id)%></span>
									</div>
									<br>
									<div style="max-width: 220px;">

									</div>
								</div>	
							</div>
						</td>
					<td style="border-bottom:1px solid #f2f2f2;vertical-align: middle;">
							<div class="wrap">
								<button style="height: 14px;visibility: visible;overflow: hidden; margin-left:18px;">
									<span style="display: inline-block;position: relative;top: 1px;width: 14px;height: 12px;background: url(//cdnimg.melon.co.kr/resource/image/web/common/bullet_icons_sprite_20201112.png) no-repeat -69px -15px;vertical-align: top;line-height: 0;font-size: 0; overflow: hidden;"></span>
									<span style="color: #888;line-height: 14px;font-size: 12px;letter-spacing: 0;vertical-align: top;"><%= play_list.track.recommend %></span>
								</button>
								
							</div>
						</td>
					<td style="border-bottom: 1px solid #f2f2f2;text-align: left;vertical-align: middle;">
							<div style="text-align:center;">
								<%= audio_tag play_list.track.track_play, controls: "controls" , class: "my_audio",  style: "width: 19px;height: 28px;"%>
							</div>
						</td>
					<td style="border-bottom: 1px solid #f2f2f2;text-align: left;vertical-align: middle;">
							<div style="text-align:center;">
								<button type="button" style="width: 19px;height: 28px;background-position: -45px -30px;background-position-y: -58px;background-image: url(//cdnimg.melon.co.kr/resource/image/web/common/button_icons_sprite_20200521.png);">
								</button>
							</div>
						</td>
					<td style="border-bottom: 1px solid #f2f2f2;text-align: left;vertical-align: middle;">
							<div style="text-align:center;">
								<button type="button" style="width: 21px;height: 24px;background-position: -98px -30px;background-image: url(//cdnimg.melon.co.kr/resource/image/web/common/button_icons_sprite_20200521.png);background-position-y: -58px;">
								</button>
							</div>
					</td>
					<td style="border-bottom: 1px solid #f2f2f2;text-align: left;vertical-align: middle;">
							<div style="text-align:center;">
								<button type="button" style="width: 24px;height: 28px;background-position: -152px -30px;background-position-y: -58px;background-image: url(//cdnimg.melon.co.kr/resource/image/web/common/button_icons_sprite_20200521.png);">
								</button>
							</div>
						</td>
				</tr>
				<% end %>
			</tbody>
		</table>
			
		</div>
	</div>
</div>

app/views/play_lists/new.html.erb
<h1>New Play List</h1>

<%= render 'form', play_list: @play_list %>

<%= link_to 'Back', play_lists_path %>

app/views/play_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @play_list.user %>
</p>

<p>
  <strong>Track:</strong>
  <%= @play_list.track %>
</p>

<%= link_to 'Edit', edit_play_list_path(@play_list) %> |
<%= link_to 'Back', play_lists_path %>