config/routes.rb
Rails.application.routes.draw do
  resources :play_lists
  resources :videos
  resources :payusers
  resources :commends
  devise_for :users ,:controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  
  get 'home/index', to: 'home#index', as: :home
  resources :tracks
  resources :albums
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get 'albums/:album_id/show_albums', to: 'albums#show', as: :album_show
	get 'artists/:id/show_album', to: 'artists#show_album', as: :artists_show_album
	get 'artists/:id/show_track', to: 'artists#show_track', as: :artists_show_track
	get 'artists/:id/show_video', to: 'artists#show_video', as: :artists_show_video
	match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
	root 'home#index'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :tracks ,dependent: :destroy
  has_many :commends ,dependent: :destroy
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :albums ,dependent: :destroy
end

app/models/commend.rb
class Commend < ApplicationRecord
  # resourcify
  # include Authority::Abilities
  belongs_to :user
  belongs_to :album
	

end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/payuser.rb
class Payuser < ApplicationRecord
end

app/models/play_list.rb
class PlayList < ApplicationRecord
  belongs_to :user
  belongs_to :track
	
	def overlap?
	PlayList.where(user_id: self.user_id, track_id: self.track_id).size >0
	end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/social_auth.rb
class SocialAuth < ApplicationRecord
	belongs_to :user
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
  has_one :video
  has_many :users, :through => :play_lists
end

app/models/user.rb
class User < ApplicationRecord
  # rolify
  # include Authority::UserAbilities	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable,:omniauthable
  has_many :identities, dependent: :destroy
  has_many :commends, dependent: :destroy
  has_many :tracks, :through => :play_lists
 # after_create :set_default_role, if: Proc.new { User.count > 1 }

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  validates_presence_of :name
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.info.name || auth.extra.nickname ||  auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end

    user

  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

 #  private
 #  def set_default_role
 #    add_role :user
 #  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :track
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
	@payuser = Payuser.new
  end

  # GET /artists/1 or /artists/1.json
  def show
	  @payuser = Payuser.new
  end
  def show_track
	  @payuser = Payuser.new
	  @artist = Artist.find(params[:id])
	  @albums = Album.all
	  @ar_albums = Album.where(artist_id: @artist.id)
	  @tracks = Track.all
  end
  
  def show_album
	  @payuser = Payuser.new
	  @artist = Artist.find(params[:id])
	  @albums = Album.all
	  @ar_albums = Album.where(artist_id: @artist.id) 
  end
  def show_video
	  @payuser = Payuser.new
	  @artist = Artist.find(params[:id])
	  @albums = Album.all
	  @ar_albums = Album.where(artist_id: @artist.id)
	  @tracks = Track.all
	  @videos = Video.all
		
	  if user_signed_in? 
		@pay_t = Payuser.where(user_id: current_user.id).size > 0
	  end
  end
  # GET /artists/new
  def new
    @artist = Artist.new
	  @artist = Artist.find(params[:id])
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:debut_day, :birth_day, :intro, :agency, :nationality,   :activity_name,:real_name,:sex, :activity_type, :nickname, :award_history, :link, :genre)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/commends_helper.rb
module CommendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payusers_helper.rb
module PayusersHelper
end

app/helpers/play_lists_helper.rb
module PlayListsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>



<table>
  <tbody>
    <% @artists.each do |artist| %>
      <tr>
		<td><%= artist.id %></td>
	    <td><%= artist.activity_name %></td>
	    <td><%= artist.agency %></td>
        <td><%= artist.debut_day %></td>
        <td><%= artist.birth_day %></td>
		<td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show_album.html.erb
<p id="notice"><%= notice %></p>
<div class = "cont_wrap" style="margin:0 auto; background:0; zoom:1;">
	<div class = "fold" style = "padding: 0 20px; position:relative; width:1008px; margin:0 auto;">
		<div class = "cont" style = "position; relative; z-index:10; display:block; width:1008px; min-height:800px; padding:29px 0 88px; zoom:1;">
<h2 style="color: #1a1a1a; font-weight: bold;font-size: 24px;line-height: 30px; font-family:'Malgun Gothic'; padding-bottom:25px;">
	아티스트 채널
			</h2>
	<div class= "cont" style = "border: 1px solid #bbbbbb; border-top: 2px solid #808080; height:270px; margin:0; padding:0; display: block; vertical-align: baseline;">
		<div class="atisit_img" style="position:relative; float:left; width:208px; padding:29px 20px 45px;">
			<img src="<%= @artist.link %>" style = "width: 208px; height: 208px;">	
		</div>
	
	<div class="artist_Information" style="float:left; width:440px; margin-left:22px; margin-top:29px;">
		<p style="leter-spacing: -1px;color: #1a1a1a; font-family:'Malgun Gothic'; font-weight: bold;font-size: 24px;line-height: 30px;">
			<%= @artist.activity_name %>
			<span style = "font-size:16px; font-family:'Malgun Gothic';"><%= @artist.real_name %></span>
		</p>
		<dl class = "atist_info" style = "margin-top:19px; display:block;">
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">데뷔</dt>

	
			<dd style = "loat: left;width: 368px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display: inline-block;"><%= @artist.debut_day %></span>
			</dd>
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">생일</dt>
			<dd style = "loat: left;width: 368px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display: inline-block;"><%= @artist.birth_day %></span>
			</dd>
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">활동유형</dt>
			<dd style = "loat: left;width: 368px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display: inline-block;"><%= @artist.activity_type %></span>
			</dd>
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">소속사</dt>
			<dd style = "loat: left;width: 368px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display: inline-block;"><%= @artist.agency %></span>
			</dd>
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">수상이력</dt>
			<dd style = "float: left; max-width: 315px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display:inline-block; text-overflow:ellipsis; overflow:hidden; white-space:nowrap; width:200px;"><%= @artist.award_history %></span>
			</dd>
			<a herf="@id/atist_infor" style="display:inline-block; margin-left:10px;">
				<span class = "btn"style ="display: inline;color: #666;font-size: 11px;line-height: 1.2em;letter-spacing: -1px;">더보기</span>
			</a>
		</dl>
		<dl class="atist_sns" style="margin-top:11px; zoom:1; display:block;">
			<a class="btn" href="">
			<dt style="clear: left;float: left;width: 90px;padding-left: 2px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';"> <%= link_to "수록곡으로가기",artists_show_track_path(@artist.id)%></dt>
			</a>
		</dl>
			</div>
			</div>
			<div class="wrap_tab_atists" style="font-family: 'Malgun Gothic'; ">
				<ul style="width: 1008px;margin-top: 15px;border-top: 2px solid #838383;border-bottom: 1px solid #dbdbdb;background: #eaefeb;list-style: none;height:34px;">
					<li style="float: left;width: 25%; border-right: 1px solid #dbdbdb; height: 34px;">
						<span id = "atist_infor"style ="display: block;position: relative;padding: 10px 0 7px 0px;color: #1b1b1b;text-align: center;">
						<span style ="color: #1b1b1b; ">
							<span style = "text-align: center; top: 9px; width: 20px; height: 20px;"><%= link_to "상세 정보", artist_path(@artist.id)%></span>
							</span>
						</span>
					</li>
					<li style=" float: left;width: 25%; border-right: 1px solid #dbdbdb; height: 34px;">
						<span href = "" style ="display: block;position: relative;padding: 10px 0 7px 0px;color: #1b1b1b;text-align: center;">
						<span style ="color: #1b1b1b; text-align: center;">
							<span style = "top: 9px; width: 20px; height: 20px;"><%= link_to "수록곡" , artists_show_track_path(@artist.id)%></span>
							</span>
						</span>
					</li>
					<li style=" float: left;width: 25%; height: 34px;border-right: 1px solid #dbdbdb;">
						<span href = "" style ="display: block;position: relative;padding: 10px 0 0px 0px;color: #1b1b1b;text-align: center;">
						<span style ="color: #1b1b1b; text-align: center;">
							<span style = "top: 9px; width: 18px; height: 20px;"><%= link_to "앨범", artists_show_album_path(@artist.id)%></span>
							</span>
						</span>
					</li>
					<li style=" float: left;width: 24%; height: 34px;">
						<span href = "" style ="display: block;position: relative;padding: 10px 0 0px 0px;color: #1b1b1b;text-align: center;">
						<span style ="color: #1b1b1b; text-align: center;">
							<span style = "top: 9px; width: 18px; height: 20px;"><%= link_to "비디오", artists_show_video_path(@artist.id)%></span>
							</span>
						</span>
					</li>
				</ul>
			</div>
			
			<div class="section_cont" style="border-bottom:1px solid #1a1a1a;">
				<div class="sort_info" style="padding:24px 0 30px; ">
					<div class="wrap_sort" style=" float:left; color: #1a1a1a;">
						<h5 style="margin-right:8px; color: #1a1a1a;text-decoration: none; font-size:20px;">전체앨범</h5>
					</div>
				</div>
			</div>
				<div>
			<div class="page_list margin-top:10px;">
				<div class = "list_albums" style="border-bottom: 1px solid #ccc;background: url(//cdnimg.melon.co.kr/resource/image/web/common/bg_list_album11.png) repeat 0 0;">
					<% @ar_albums.each do |album| %>
					<ul style="margin-bottom: -1px;">
						<li style="float: left;width: 320px;margin: 0 16px 0 0;padding: 16px 0 17px;border-bottom: 1px solid #ccc;">
							<div style="position:relative;">
								<span style="display: block;position: absolute;width: 130px;height: 130px;text-decoration: none;">
									<span style="    position: absolute;top: 0;left: 0;width: 130px;height: 130px;background: url(//cdnimg.melon.co.kr/resource/image/web/common/bg_frame_album04.png) no-repeat 0 0;"></span>
									<img style=" width: 130px;aspect-ratio: auto 130 / 130;height: 130px;" src="<%= album.album_link %>">
								</span>
								<div style="height: 130px; padding: 0 0 0 146px;">
									<dl>
										<dt style="height: 30px;padding: 2px 0 0;font-weight: bold;font-size: 12px;line-height: 14px;color: #1a1a1a;">
										<span style="    display: inline-block;width: auto;max-width: 100%;color: #555;white-space: nowrap;text-overflow: ellipsis;overflow: hidden;"><%= link_to album.title, album_path(album.id) %></span>
										</dt>
										<dd style="display: block;width: 100%;color: #79a54c;white-space: nowrap;text-overflow: ellipsis;"> <%= album.artist.activity_name %></dd>
										<dd style="margin: 3px 0 0;height: 17px; margin-top:63px;">
											<span style="color: #777;font-size: 12px;line-height: 14px;"><%= album.release_day%></span>
											<em style="color: #d9d9d9;font-style: normal;font-size: 11px;line-height: 14px;">|</em>
											<span style="color: #777;font-size: 12px;line-height: 14px;"><%= album.tracks.size %>곡</span>
											<em style="color: #d9d9d9;font-style: normal;font-size: 11px;line-height: 14px;">|</em>
											<div style="display: inline-block;position: relative;padding-left: 15px;color: #777 !important;font-size: 12px;line-height: 14px;">
											<span style="display: block;position: absolute;top: 2px;left: 0;width: 11px;height: 10px;
    background: url(//cdnimg.melon.co.kr/resource/image/web/common/bg_sprite_like.png) no-repeat 0 0;font-size: 0;line-height: 0;"></span>
											<%= album.recommend %>
											</div>
										</dd>
									</dl>
								</div>
							</div>
						</li>
						
					</ul>
					<%end%>
					
				</div>
			</div>
		
	</div>

			
				

app/views/artists/show_video.html.erb
<p id="notice"><%= notice %></p>
<div class = "cont_wrap" style="margin:0 auto; background:0; zoom:1;">
	<div class = "fold" style = "padding: 0 20px; position:relative; width:1008px; margin:0 auto;">
		<div class = "cont" style = "position; relative; z-index:10; display:block; width:1008px; min-height:800px; padding:29px 0 88px; zoom:1;">
<h2 style="color: #1a1a1a; font-weight: bold;font-size: 24px;line-height: 30px; font-family:'Malgun Gothic'; padding-bottom:25px;">
	아티스트 채널
			</h2>
	<div class= "cont" style = "border: 1px solid #bbbbbb; border-top: 2px solid #808080; height:270px; margin:0; padding:0; display: block; vertical-align: baseline;">
		<div class="atisit_img" style="position:relative; float:left; width:208px; padding:29px 20px 45px;">
			<img src="<%= @artist.link %>" style = "width: 208px; height: 208px;">	
		</div>
	
	<div class="artist_Information" style="float:left; width:440px; margin-left:22px; margin-top:29px;">
		<p style="leter-spacing: -1px;color: #1a1a1a; font-family:'Malgun Gothic'; font-weight: bold;font-size: 24px;line-height: 30px;">
			<%= @artist.activity_name %>
			<span style = "font-size:16px; font-family:'Malgun Gothic';"><%= @artist.real_name %></span>
		</p>
		<dl class = "atist_info" style = "margin-top:19px; display:block;">
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">데뷔</dt>

	
			<dd style = "loat: left;width: 368px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display: inline-block;"><%= @artist.debut_day %></span>
			</dd>
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">생일</dt>
			<dd style = "loat: left;width: 368px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display: inline-block;"><%= @artist.birth_day %></span>
			</dd>
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">활동유형</dt>
			<dd style = "loat: left;width: 368px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display: inline-block;"><%= @artist.activity_type %></span>
			</dd>
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">소속사</dt>
			<dd style = "loat: left;width: 368px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display: inline-block;"><%= @artist.agency %></span>
			</dd>
			<dt style="clear: left;float: left;width: 70px;padding-left: 2px;color: #666;font-size: 12px;line-height: 20px;">수상이력</dt>
			<dd style = "float: left; max-width: 315px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';">
			<span style="display:inline-block; text-overflow:ellipsis; overflow:hidden; white-space:nowrap; width:200px;"><%= @artist.award_history %></span>
			</dd>
			<a herf="@id/atist_infor" style="display:inline-block; margin-left:10px;">
				<span class = "btn"style ="display: inline;color: #666;font-size: 11px;line-height: 1.2em;letter-spacing: -1px;">더보기</span>
			</a>
		</dl>
		<dl class="atist_sns" style="margin-top:11px; zoom:1; display:block;">
			<a class="btn" href="">
			<dt style="clear: left;float: left;width: 90px;padding-left: 2px;color: #1a1a1a;font-size: 12px;line-height: 20px;font-family: 'Malgun Gothic';"> <%= link_to "수록곡으로가기",artists_show_track_path(@artist.id)%></dt>
			</a>
		</dl>
			</div>
			</div>
			<div class="wrap_tab_atists" style="font-family: 'Malgun Gothic'; ">
				<ul style="width: 1008px;margin-top: 15px;border-top: 2px solid #838383;border-bottom: 1px solid #dbdbdb;background: #eaefeb;list-style: none;height:34px;">
					<li style="float: left;width: 25%; border-right: 1px solid #dbdbdb; height: 34px;">
						<span id = "atist_infor"style ="display: block;position: relative;padding: 10px 0 7px 0px;color: #1b1b1b;text-align: center;">
						<span style ="color: #1b1b1b; ">
							<span style = "text-align: center; top: 9px; width: 20px; height: 20px;"><%= link_to "상세 정보", artist_path(@artist.id)%></span>
							</span>
						</span>
					</li>
					<li style=" float: left;width: 25%; border-right: 1px solid #dbdbdb; height: 34px;">
						<span href = "" style ="display: block;position: relative;padding: 10px 0 7px 0px;color: #1b1b1b;text-align: center;">
						<span style ="color: #1b1b1b; text-align: center;">
							<span style = "top: 9px; width: 20px; height: 20px;"><%= link_to "수록곡" , artists_show_track_path(@artist.id)%></span>
							</span>
						</span>
					</li>
					<li style=" float: left;width: 25%; height: 34px;border-right: 1px solid #dbdbdb;">
						<span href = "" style ="display: block;position: relative;padding: 10px 0 0px 0px;color: #1b1b1b;text-align: center;">
						<span style ="color: #1b1b1b; text-align: center;">
							<span style = "top: 9px; width: 18px; height: 20px;"><%= link_to "앨범", artists_show_album_path(@artist.id)%></span>
							</span>
						</span>
					</li>
					<li style=" float: left;width: 24%; height: 34px;">
						<span href = "" style ="display: block;position: relative;padding: 10px 0 0px 0px;color: #1b1b1b;text-align: center;">
						<span style ="color: #1b1b1b; text-align: center;">
							<span style = "top: 9px; width: 18px; height: 20px;"><%= link_to "비디오", artists_show_video_path(@artist.id)%></span>
							</span>
						</span>
					</li>
				</ul>
			</div>
			<div class="info">
			<div class="section_cont" style="border-bottom:1px solid #1a1a1a;">
				<div class="sort_info" style="padding:24px 0 30px; ">
					<div class="wrap_sort" style=" float:left; color: #1a1a1a;">
						<h5 style="margin-right:8px; color: #1a1a1a;text-decoration: none; font-size:20px;">비디오</h5>
					</div>
				</div>
			</div>
					<div class="page_list margin-top:10px;">
				<div class = "list_albums" style="">
			<ul style="margin-bottom: -1px;margin: 0 0 20px 5px;">
				<% @ar_albums.each do |album| %>
				
					<% @tracks.each do |track| %>
					
						<% if album.id == track.album_id %>
							<% @videos.each do |video| %>
								<% if track.id == video.track_id %>
										<% if @pay_t %>
					<li style=" float: left;margin-left:10px;">
									<iframe width="320" height="230" src="<%= video.link%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
									<p style="font-size:14px;"> <%= link_to video.track.title, video_path(video.id)%></p>
									<p style="font-size:14px;"> <%= link_to video.track.album.artist.activity_name, artist_path(video.track.album.artist.id), style:"color: #00b423;"%></p>
										
									<span style="display: inline-block;position: relative;top: 1px;width: 14px;height: 12px;background: url(//cdnimg.melon.co.kr/resource/image/web/common/bullet_icons_sprite_20201112.png) no-repeat -69px -15px;vertical-align: top;line-height: 0;font-size: 0;">
										</span>	
									<span style="color: #888;line-height: 14px;font-size: 12px;letter-spacing: 0;vertical-align: top;"><%=  video.track.recommend%></span>
									</li>
					
										<% else %>
											<li style="float: left;margin-left:10px;">
									<iframe width="320" height="230" src="<%= video.link%>?start=0&end=60" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
									<p style="font-size:14px;"> <%= link_to video.track.title, video_path(video.id)%></p>
									<p style="font-size:14px;"> <%= link_to video.track.album.artist.activity_name, artist_path(video.track.album.artist.id), style:"color: #00b423;"%></p>
										
									<span style="display: inline-block;position: relative;top: 1px;width: 14px;height: 12px;background: url(//cdnimg.melon.co.kr/resource/image/web/common/bullet_icons_sprite_20201112.png) no-repeat -69px -15px;vertical-align: top;line-height: 0;font-size: 0;">
										</span>	
									<span style="color: #888;line-height: 14px;font-size: 12px;letter-spacing: 0;vertical-align: top;"><%=  video.track.recommend%></span>
									</li>
										<%end%>
								<%end%>		
							<%end%>
						<%end%>
					<%end%>
				<%end%>	
						</ul>
						</div>
				</div>
			</div>