config/routes.rb
Rails.application.routes.draw do
  resources :play_lists
  resources :videos
  resources :payusers
  resources :commends
  devise_for :users ,:controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  
  get 'home/index', to: 'home#index', as: :home
  resources :tracks
  resources :albums
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get 'albums/:album_id/show_albums', to: 'albums#show', as: :album_show
	get 'artists/:id/show_album', to: 'artists#show_album', as: :artists_show_album
	get 'artists/:id/show_track', to: 'artists#show_track', as: :artists_show_track
	get 'artists/:id/show_video', to: 'artists#show_video', as: :artists_show_video
	match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
	root 'home#index'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :tracks ,dependent: :destroy
  has_many :commends ,dependent: :destroy
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :albums ,dependent: :destroy
end

app/models/commend.rb
class Commend < ApplicationRecord
  # resourcify
  # include Authority::Abilities
  belongs_to :user
  belongs_to :album
	

end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/payuser.rb
class Payuser < ApplicationRecord
end

app/models/play_list.rb
class PlayList < ApplicationRecord
  belongs_to :user
  belongs_to :track
	
	def overlap?
	PlayList.where(user_id: self.user_id, track_id: self.track_id).size >0
	end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/social_auth.rb
class SocialAuth < ApplicationRecord
	belongs_to :user
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
  has_one :video
  has_many :users, :through => :play_lists
end

app/models/user.rb
class User < ApplicationRecord
  # rolify
  # include Authority::UserAbilities	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable,:omniauthable
  has_many :identities, dependent: :destroy
  has_many :commends, dependent: :destroy
  has_many :tracks, :through => :play_lists
 # after_create :set_default_role, if: Proc.new { User.count > 1 }

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  validates_presence_of :name
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.info.name || auth.extra.nickname ||  auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end

    user

  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

 #  private
 #  def set_default_role
 #    add_role :user
 #  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :track
end

app/controllers/commends_controller.rb
class CommendsController < ApplicationController
  before_action :set_commend, only: %i[ show edit update destroy ]

  # GET /commends or /commends.json
  def index
    @commends = Commend.all
  end

  # GET /commends/1 or /commends/1.json
  def show
  end

  # GET /commends/new
  def new
    @commend = Commend.new
  end

  # GET /commends/1/edit
  def edit
  end

  # POST /commends or /commends.json
  def create
    @commend = Commend.new(commend_params)

    respond_to do |format|
      if @commend.save
        format.html { redirect_to album_path(@commend.album_id), notice: "Commend was successfully created." }
        format.json { render :show, status: :created, location: @commend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @commend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commends/1 or /commends/1.json
  def update
    respond_to do |format|
      if @commend.update(commend_params)
        format.html { redirect_to commend_url(@commend), notice: "Commend was successfully updated." }
        format.json { render :show, status: :ok, location: @commend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @commend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commends/1 or /commends/1.json
  def destroy
    @commend.destroy
	  
    respond_to do |format|
	 
      format.html {  redirect_to album_path(@commend.album_id), notice: "Commend was successfully destroyed." }
      format.json { head :no_content }
	 # else
	 # format.html{ redirect_to album_path(@commend.album_id), notice: "본인이 작성한 댓글만 삭제가 가능합니다." }
	 # end
  end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commend
      @commend = Commend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def commend_params
      params.require(:commend).permit(:commend, :user_id, :album_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/commends_helper.rb
module CommendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payusers_helper.rb
module PayusersHelper
end

app/helpers/play_lists_helper.rb
module PlayListsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/commends/_form.html.erb
<%= form_with(model: commend, local: true) do |form| %>
  
	<% if user_signed_in? %>
  	<div class="field" style="margin-top:100px;" >
	  <%= form.label :commend,"댓글" ,style:"font-size:15px;"%>
	  <div style="width:1008px;background-color: #f5f5f5;height:142px;display:block; margin-top:5px;">
		  <div style="position:relative; float:left; margin-top:30px; margin-left:20px;">
			  <img  style="width: 54px;height: 54px;" src="<%=current_user.profile_img%>">
			  
		<%end%>
		  </div>
		<%= form.text_area :commend , class:"commend_text "%>
		 <%= form.submit :commend , style:" width:72px; height:80px; margin-bottom:85px;margin-left:5px;" %>
	</div>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id , value: current_user.id%>
  </div>

  <div class="field">
    <%= form.hidden_field :album_id, value: @album.id %>
  </div>
<% end %>

app/views/commends/edit.html.erb
<h1>Editing Commend</h1>

<%= render 'form', commend: @commend %>

<%= link_to 'Show', @commend %> |
<%= link_to 'Back', commends_path %>

app/views/commends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commends</h1>

<table>
  <thead>
    <tr>
      <th>Commend</th>
      <th>User</th>
      <th>Album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commends.each do |commend| %>
      <tr>
        <td><%= commend.commend %></td>
        <td><%= commend.user %></td>
        <td><%= commend.album %></td>
        <td><%= link_to 'Show', commend %></td>
        <td><%= link_to 'Edit', edit_commend_path(commend) %></td>
        <td><%= link_to 'Destroy', commend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commend', new_commend_path %>

app/views/commends/new.html.erb
<h1>New Commend</h1>

<%= render 'form', commend: @commend %>

<%= link_to 'Back', commends_path %>

app/views/commends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commend:</strong>
  <%= @commend.commend %>
</p>

<p>
  <strong>User:</strong>
  <%= @commend.user %>
</p>

<p>
  <strong>Album:</strong>
  <%= @commend.album %>
</p>

<%= link_to 'Edit', edit_commend_path(@commend) %> |
<%= link_to 'Back', commends_path %>