config/routes.rb
Rails.application.routes.draw do
  resources :play_lists
  resources :videos
  resources :payusers
  resources :commends
  devise_for :users ,:controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  
  get 'home/index', to: 'home#index', as: :home
  resources :tracks
  resources :albums
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get 'albums/:album_id/show_albums', to: 'albums#show', as: :album_show
	get 'artists/:id/show_album', to: 'artists#show_album', as: :artists_show_album
	get 'artists/:id/show_track', to: 'artists#show_track', as: :artists_show_track
	get 'artists/:id/show_video', to: 'artists#show_video', as: :artists_show_video
	match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
	root 'home#index'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :tracks ,dependent: :destroy
  has_many :commends ,dependent: :destroy
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :albums ,dependent: :destroy
end

app/models/commend.rb
class Commend < ApplicationRecord
  # resourcify
  # include Authority::Abilities
  belongs_to :user
  belongs_to :album
	

end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/payuser.rb
class Payuser < ApplicationRecord
end

app/models/play_list.rb
class PlayList < ApplicationRecord
  belongs_to :user
  belongs_to :track
	
	def overlap?
	PlayList.where(user_id: self.user_id, track_id: self.track_id).size >0
	end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/social_auth.rb
class SocialAuth < ApplicationRecord
	belongs_to :user
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
  has_one :video
  has_many :users, :through => :play_lists
end

app/models/user.rb
class User < ApplicationRecord
  # rolify
  # include Authority::UserAbilities	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable,:omniauthable
  has_many :identities, dependent: :destroy
  has_many :commends, dependent: :destroy
  has_many :tracks, :through => :play_lists
 # after_create :set_default_role, if: Proc.new { User.count > 1 }

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  validates_presence_of :name
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.info.name || auth.extra.nickname ||  auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end

    user

  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

 #  private
 #  def set_default_role
 #    add_role :user
 #  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :track
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
	  @payuser = Payuser.new
  end

  # GET /videos/1 or /videos/1.json
  def show
	  
	  if user_signed_in? 
		@pay_t = Payuser.where(user_id: current_user.id).size > 0
	  end
  	  @payuser = Payuser.new
	  @tracks = Track.all
	  @videos = Video.all
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:link, :intro, :track_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/commends_helper.rb
module CommendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payusers_helper.rb
module PayusersHelper
end

app/helpers/play_lists_helper.rb
module PlayListsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_area :link %>
  </div>

  <div class="field">
    <%= form.label :intro %>
    <%= form.text_area :intro %>
  </div>

  <div class="field">
    <%= form.label :track_id %>
    <%= form.text_field :track_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Intro</th>
      <th>Track</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.link %></td>
        <td><%= video.intro %></td>
        <td><%= video.track %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

		<div class = "cont_wrap" style="margin:0 auto; background:0; zoom:1;">
			<div class="cont_info" style="position: relative;width: 1008px;margin: 0 auto;padding: 0 20px;">
				
		
		<div class="video" style="position: relative;z-index: 10;display: block;width: 1008px;min-height: 800px;padding: 29px 0 88px;zoom: 1;">
			<div class="page_header" style="position:relative; margin-bottom:8px;">
			<h2 style="height: 40px;line-height: 40px;font-size: 26px;">영상 정보
			</h2>
		</div>
			<div style="width: 1008px;height: 568px;">
				<% if @pay_t %>
<iframe style="width:100%; height:100%;" src="<%= @video.link%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<% else %>
<iframe style="width:100%; height:100%;" src="<%= @video.link%>?start=0&end=60" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<% end %>
				
			</div>
			<div class="video_info" style="margin-bottom:35px;">
				<div class="header" style="position:relative; padding: 24px 0 22px; border-bottom:1px solid #e5e5e5;">
					<h3 style="margin-right: 200px;line-height: 1.3em;color: #333;font-size: 24px;">
						[MV]<%= @video.track.title %>
					</h3>
					<span style="display: inline-block;position: relative;top: 1px;width: 14px;height: 12px;background: url(//cdnimg.melon.co.kr/resource/image/web/common/bullet_icons_sprite_20201112.png) no-repeat -69px -15px;vertical-align: top;line-height: 0;font-size: 0;margin-top:20px;">
									<span style="margin-left:30px;margin-top:20px;color: #888;line-height: 14px;font-size: 16px;letter-spacing: 0;vertical-align: top;"><%= @video.track.recommend %></span></span>
				<div class="meta" style="position: absolute;right: 0;bottom: 25px;">
					<span style="color: #606060;font-size: 16px;vertical-align: top;"><%= @video.track.album.release_day %></span>
				</div>
				</div>
				<div class="vdo_artist" style="margin-top: 24px;">
					<div class="thumb" style="float: left;width: 80px;height: 80px;border-radius: 100px;">
						<span style="display: block;position: relative; font-size: 0;line-height: 0;color: #1a1a1a;text-decoration: none;">
						<img style="border-radius: 100px;width: 80px;aspect-ratio: auto 80 / 80;height: 80px;" src="<%= @video.track.album.artist.link%>">
							<span style="border-radius: 100px;"></span>
						</span>
					</div>
					<div class="entry" style="float: left;padding: 18px 0 0 14px;">
						<div class="artist">
							<%=link_to @video.track.album.artist.activity_name , artist_path(@video.track.album.artist.id),style:"color: #00b423;font-size: 18px;" %>

						</div>
					</div>
				</div>
				
			</div>
			
</div>
<div class="section_videoinfo">
				<div class="header" style="position: relative;margin-bottom: 8px;">
					<h5 style="height: 28px;line-height: 28px;font-size: 20px;">
						비디오소개
					</h5>
				</div>
	<div class="cont_info" style="position: relative;padding: 5px 0 45px;">
		<div style="    height: 77px;line-height: 24px;color: #767676;font-size: 14px;overflow: hidden;">
			<%= @video.intro%>
		</div>
	</div>
			</div>


<div class="section_movie" style="position: relative; margin-bottom: 35px;margin-top:50px;">
					<div style="position: relative; margin-bottom: 8px;">
						<h5 style="height: 28px;line-height: 28px;font-size: 20px;">관련 영상</h5>
					
				</div>
					<div class="service_video_list">	
						<ul style="margin: 0 0 0 -20px;display: block;">
<% @tracks.each do |track| %>
	<% if track.album.id == @video.track.album.id %>
		<% @videos.each do |video| %>

			<% if video.track.id == track.id %>
				<% if video.id != @video.id %>
					<% if @pay_t %>
					<li style="width: 237px; margin: 0 0 0 20px;float: left;">
									<iframe width="237" height="139" src="<%= video.link%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
									<p style="font-size:14px;"> <%= link_to video.track.title, video_path(video.id)%></p>
									<p style="font-size:14px;"> <%= link_to video.track.album.artist.activity_name, artist_path(video.track.album.artist.id), style:"color: #00b423;"%></p>
										
									<span style="display: inline-block;position: relative;top: 1px;width: 14px;height: 12px;background: url(//cdnimg.melon.co.kr/resource/image/web/common/bullet_icons_sprite_20201112.png) no-repeat -69px -15px;vertical-align: top;line-height: 0;font-size: 0;">
										</span>	
									<span style="color: #888;line-height: 14px;font-size: 12px;letter-spacing: 0;vertical-align: top;"><%=  video.track.recommend%></span>
									</li>
					<% else %>
					<li style="width: 237px; margin: 0 0 0 20px;float: left;">
									<iframe width="237" height="139" src="<%= video.link%>?start=0&end=60" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
									<p style="font-size:14px;"> <%= link_to video.track.title, video_path(video.id)%></p>
									<p style="font-size:14px;"> <%= link_to video.track.album.artist.activity_name, artist_path(video.track.album.artist.id), style:"color: #00b423;"%></p>
										
									<span style="display: inline-block;position: relative;top: 1px;width: 14px;height: 12px;background: url(//cdnimg.melon.co.kr/resource/image/web/common/bullet_icons_sprite_20201112.png) no-repeat -69px -15px;vertical-align: top;line-height: 0;font-size: 0;">
										</span>	
									<span style="color: #888;line-height: 14px;font-size: 12px;letter-spacing: 0;vertical-align: top;"><%=  video.track.recommend%></span>
									</li>
					<%end%>
				<%end %>
			<%end %>			
		<%end %>
	<%end %>
<%end %>
							</ul>
			</div>
				<div class="page" style="position: absolute;top: 4px;right: 0;">
					<span style="display: inline-block;margin-left: 3px;vertical-align: middle;">
					<a style="float: left;margin-right: -1px;position: relative;width: 23px;height: 23px;border: 1px solid #ccc;">
					<span style="top: 50%;left: 50%;width: 7px;height: 11px;margin: -6px 0 0 -3px;display: block;position: relative;
background: url(//cdnimg.melon.co.kr/resource/image/web/common/button_icons_sprite_20200521.png) no-repeat -459px 0;font-size: 0;line-height: 0;background-position: -459px -14px;">이전</span>
					</a>
					<a style="position: relative;width: 23px;height: 23px;border: 1px solid #ccc;float: left;margin-right: 0;">
					<span style="top: 50%;left: 50%;width: 7px;height: 11px;margin: -6px 0 0 -3px;display: block;position: relative;
background: url(//cdnimg.melon.co.kr/resource/image/web/common/button_icons_sprite_20200521.png) no-repeat -459px 0;font-size: 0;line-height: 0;background-position: -469px -14px;">다음</span>
					</a>
						</span>
				</div>
		</div>
</div>
</div>